### ISSUE TITLE
Expression produces a union type that is too complex to represent.ts(2590)

### ISSUE THREAD

**Issue by tizayi** [DiamondLightSource/dedi-web#62]
Maybe it's to do with with the typescript version.

**Comment by stan-dot** [comment]
which file is this located in?

**Comment by tizayi** [comment]
centrePlot.tsx

**Comment by stan-dot** [comment]
https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t

here's a solution, it's a vscode issue
